### ISSUE TITLE
Is it OpenSSL really needed?

### ISSUE THREAD

**Issue by kidandcat** [mhe/gabi#3]
We would want to know if Safe primes are really needed.
https://security.stackexchange.com/questions/73505/use-of-safe-prime-in-rsa-digital-signature-scheme/73542#73542

We are building a software on top of this library but we wouldn't want to have OpenSSL (and so, Cgo) as dependencies.

Go devs removed the use of safe primes for RSA generation on crypto package arguing that not using them for priv/pub rsa key generation is secure enough and that OpenSSL does not use them too.
https://codereview.appspot.com/253041/show

So, do you consider it necesary to use Safe Primes?

**Comment by mhe** [comment]
Safe primes are needed for the type of cryptography used in this library. There is a Go-only version included in the code. The reason credentials/safeprime is used is purely for performance reasons.

**Comment by kidandcat** [comment]
Thank you

**Comment by confiks** [comment]
@kidandcat 

If the concern is that it should be possible to build gabi outside of `cgo`, a simple `cgo` exclusion/inclusion build flag could be added to `safeprime.go` / `safeprime_stub.go` of the `credentials/safeprime` repository as is currently done for Android, iOS and Windows. That would probably be better anyway. Gabi would then panic when trying to generate a key without `cgo` (or on mobile).

If your issue is with key generation itself, we removed [the pure Go implementation](https://github.com/credentials/safeprime/tree/go) of the prime generation, because it really is too slow for any practical use, even on a modern PC. We also wanted to avoid having to deal with multiple possible implementation for the same thing.

**Comment by kidandcat** [comment]
@confiks Thank you very much for the explanation
